/*

 BG_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bg_tilesBank 0

/* Super Gameboy palette 0 */
#define bg_tilesSGBPal0c0 6076
#define bg_tilesSGBPal0c1 8935
#define bg_tilesSGBPal0c2 6596
#define bg_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bg_tilesSGBPal1c0 6076
#define bg_tilesSGBPal1c1 8935
#define bg_tilesSGBPal1c2 6596
#define bg_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bg_tilesSGBPal2c0 6076
#define bg_tilesSGBPal2c1 8935
#define bg_tilesSGBPal2c2 6596
#define bg_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bg_tilesSGBPal3c0 6076
#define bg_tilesSGBPal3c1 8935
#define bg_tilesSGBPal3c2 6596
#define bg_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bg_tilesCGBPal0c0 32767
#define bg_tilesCGBPal0c1 20383
#define bg_tilesCGBPal0c2 15166
#define bg_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bg_tilesCGBPal1c0 32767
#define bg_tilesCGBPal1c1 32725
#define bg_tilesCGBPal1c2 32623
#define bg_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define bg_tilesCGBPal2c0 32767
#define bg_tilesCGBPal2c1 21497
#define bg_tilesCGBPal2c2 16367
#define bg_tilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define bg_tilesCGBPal3c0 32767
#define bg_tilesCGBPal3c1 24382
#define bg_tilesCGBPal3c2 14943
#define bg_tilesCGBPal3c3 3171

/* Gameboy Color palette 4 */
#define bg_tilesCGBPal4c0 26425
#define bg_tilesCGBPal4c1 21140
#define bg_tilesCGBPal4c2 10570
#define bg_tilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define bg_tilesCGBPal5c0 24574
#define bg_tilesCGBPal5c1 19288
#define bg_tilesCGBPal5c2 7858
#define bg_tilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define bg_tilesCGBPal6c0 26425
#define bg_tilesCGBPal6c1 21140
#define bg_tilesCGBPal6c2 10570
#define bg_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define bg_tilesCGBPal7c0 6076
#define bg_tilesCGBPal7c1 8935
#define bg_tilesCGBPal7c2 6596
#define bg_tilesCGBPal7c3 224
/* Start of tile array. */
extern unsigned char bg_tiles[];

/* End of BG_TILES.H */
