/*

 CLOUD_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define cloud_tilesBank 0

/* Super Gameboy palette 0 */
#define cloud_tilesSGBPal0c0 0
#define cloud_tilesSGBPal0c1 0
#define cloud_tilesSGBPal0c2 0
#define cloud_tilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define cloud_tilesSGBPal1c0 6076
#define cloud_tilesSGBPal1c1 8935
#define cloud_tilesSGBPal1c2 6596
#define cloud_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define cloud_tilesSGBPal2c0 6076
#define cloud_tilesSGBPal2c1 8935
#define cloud_tilesSGBPal2c2 6596
#define cloud_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define cloud_tilesSGBPal3c0 6076
#define cloud_tilesSGBPal3c1 8935
#define cloud_tilesSGBPal3c2 6596
#define cloud_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define cloud_tilesCGBPal0c0 29520
#define cloud_tilesCGBPal0c1 30611
#define cloud_tilesCGBPal0c2 32728
#define cloud_tilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define cloud_tilesCGBPal1c0 0
#define cloud_tilesCGBPal1c1 0
#define cloud_tilesCGBPal1c2 0
#define cloud_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define cloud_tilesCGBPal2c0 132
#define cloud_tilesCGBPal2c1 4
#define cloud_tilesCGBPal2c2 0
#define cloud_tilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define cloud_tilesCGBPal3c0 31
#define cloud_tilesCGBPal3c1 32736
#define cloud_tilesCGBPal3c2 12287
#define cloud_tilesCGBPal3c3 27701

/* Gameboy Color palette 4 */
#define cloud_tilesCGBPal4c0 26641
#define cloud_tilesCGBPal4c1 7
#define cloud_tilesCGBPal4c2 0
#define cloud_tilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define cloud_tilesCGBPal5c0 0
#define cloud_tilesCGBPal5c1 0
#define cloud_tilesCGBPal5c2 0
#define cloud_tilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define cloud_tilesCGBPal6c0 0
#define cloud_tilesCGBPal6c1 0
#define cloud_tilesCGBPal6c2 0
#define cloud_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define cloud_tilesCGBPal7c0 0
#define cloud_tilesCGBPal7c1 0
#define cloud_tilesCGBPal7c2 0
#define cloud_tilesCGBPal7c3 0
/* Start of tile array. */
extern unsigned char cloud_tiles[];

/* End of CLOUD_TILES.H */
