//AUTOGENERATED FILE FROM png2asset
// Conversion args: /font_8x16_out.png -o /font_8x16_out.c -use_metafile -spr8x16 -sprite_no_optimize -keep_duplicate_tiles -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 1 -pack_mode casioloopy -tiles_only

#ifndef METASPRITE_font_8x16_out_H
#define METASPRITE_font_8x16_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_8x16_out_TILE_ORIGIN 0
#define font_8x16_out_TILE_W 8
#define font_8x16_out_TILE_H 16
#define font_8x16_out_WIDTH 360
#define font_8x16_out_HEIGHT 16
#define font_8x16_out_TILES_WIDTH 45
#define font_8x16_out_TILES_HEIGHT 1
#define font_8x16_out_TILE_COUNT 90
#define font_8x16_out_PALETTE_COUNT 1
#define font_8x16_out_COLORS_PER_PALETTE 16
#define font_8x16_out_TOTAL_COLORS 16

BANKREF_EXTERN(font_8x16_out)

extern const palette_color_t font_8x16_out_palettes[16];
extern const uint8_t font_8x16_out_tiles[2880];

#endif
