//AUTOGENERATED FILE FROM png2asset
// Conversion args: /font_8x8_nums_pet_colored.png -o /font_8x8_nums_pet_colored_out.c -use_metafile -keep_duplicate_tiles -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 1 -pack_mode casioloopy -tiles_only

#ifndef METASPRITE_font_8x8_nums_pet_colored_out_H
#define METASPRITE_font_8x8_nums_pet_colored_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_8x8_nums_pet_colored_out_TILE_ORIGIN 0
#define font_8x8_nums_pet_colored_out_TILE_W 8
#define font_8x8_nums_pet_colored_out_TILE_H 16
#define font_8x8_nums_pet_colored_out_WIDTH 8
#define font_8x8_nums_pet_colored_out_HEIGHT 320
#define font_8x8_nums_pet_colored_out_TILES_WIDTH 1
#define font_8x8_nums_pet_colored_out_TILES_HEIGHT 20
#define font_8x8_nums_pet_colored_out_TILE_COUNT 40
#define font_8x8_nums_pet_colored_out_PALETTE_COUNT 1
#define font_8x8_nums_pet_colored_out_COLORS_PER_PALETTE 16
#define font_8x8_nums_pet_colored_out_TOTAL_COLORS 16

BANKREF_EXTERN(font_8x8_nums_pet_colored_out)

extern const palette_color_t font_8x8_nums_pet_colored_out_palettes[16];
extern const uint16_t font_8x8_nums_pet_colored_out_tiles[640];

#endif
