//AUTOGENERATED FILE FROM png2asset
// Conversion args: /game_board_border.png -o /game_board_border_out.c -use_metafile -map -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 1 -pack_mode casioloopy

#ifndef METASPRITE_game_board_border_out_H
#define METASPRITE_game_board_border_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define game_board_border_out_TILE_ORIGIN 0
#define game_board_border_out_TILE_W 8
#define game_board_border_out_TILE_H 8
#define game_board_border_out_WIDTH 112
#define game_board_border_out_HEIGHT 160
#define game_board_border_out_TILES_WIDTH 14
#define game_board_border_out_TILES_HEIGHT 20
#define game_board_border_out_TILE_COUNT 21
#define game_board_border_out_PALETTE_COUNT 1
#define game_board_border_out_COLORS_PER_PALETTE 16
#define game_board_border_out_TOTAL_COLORS 16
#define game_board_border_out_MAP_ATTRIBUTES 0
#define game_board_border_out_MAP_ATTRIBUTES_WIDTH 14
#define game_board_border_out_MAP_ATTRIBUTES_HEIGHT 20
#define game_board_border_out_MAP_ATTRIBUTES_PACKED_WIDTH 14
#define game_board_border_out_MAP_ATTRIBUTES_PACKED_HEIGHT 20
extern const uint16_t game_board_border_out_map[280];
#define game_board_border_out_map_attributes game_board_border_out_map

BANKREF_EXTERN(game_board_border_out)

extern const palette_color_t game_board_border_out_palettes[16];
extern const uint16_t game_board_border_out_tiles[336];

#endif
