/*

 GAME_BOARD_MAP.H

 Map Include File.

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : intro_screen.gbm.tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define game_board_mapWidth 20
#define game_board_mapHeight 18
#define game_board_mapBank 0

#define game_board_map game_board_mapPLN0
extern const unsigned char game_board_mapPLN0[];
extern const unsigned char game_board_mapPLN1[];

/* End of GAME_BOARD_MAP.H */
