//AUTOGENERATED FILE FROM png2asset
// Conversion args: /intro_cat_out.png -o /intro_cat_out.c -use_metafile -map -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 4 -pack_mode casioloopy

#ifndef METASPRITE_intro_cat_out_H
#define METASPRITE_intro_cat_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define intro_cat_out_TILE_ORIGIN 0
#define intro_cat_out_TILE_W 8
#define intro_cat_out_TILE_H 8
#define intro_cat_out_WIDTH 256
#define intro_cat_out_HEIGHT 224
#define intro_cat_out_TILES_WIDTH 32
#define intro_cat_out_TILES_HEIGHT 28
#define intro_cat_out_TILE_COUNT 101
#define intro_cat_out_PALETTE_COUNT 2
#define intro_cat_out_COLORS_PER_PALETTE 16
#define intro_cat_out_TOTAL_COLORS 32
#define intro_cat_out_MAP_ATTRIBUTES 0
#define intro_cat_out_MAP_ATTRIBUTES_WIDTH 32
#define intro_cat_out_MAP_ATTRIBUTES_HEIGHT 28
#define intro_cat_out_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define intro_cat_out_MAP_ATTRIBUTES_PACKED_HEIGHT 28
extern const uint16_t intro_cat_out_map[896];
#define intro_cat_out_map_attributes intro_cat_out_map

BANKREF_EXTERN(intro_cat_out)

extern const palette_color_t intro_cat_out_palettes[32];
extern const uint8_t intro_cat_out_tiles[3232];

#endif
