/*

 INTRO_CAT_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define intro_cat_tilesBank 0

/* Super Gameboy palette 0 */
#define intro_cat_tilesSGBPal0c0 0
#define intro_cat_tilesSGBPal0c1 0
#define intro_cat_tilesSGBPal0c2 0
#define intro_cat_tilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define intro_cat_tilesSGBPal1c0 6076
#define intro_cat_tilesSGBPal1c1 8935
#define intro_cat_tilesSGBPal1c2 6596
#define intro_cat_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define intro_cat_tilesSGBPal2c0 6076
#define intro_cat_tilesSGBPal2c1 8935
#define intro_cat_tilesSGBPal2c2 6596
#define intro_cat_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define intro_cat_tilesSGBPal3c0 6076
#define intro_cat_tilesSGBPal3c1 8935
#define intro_cat_tilesSGBPal3c2 6596
#define intro_cat_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define intro_cat_tilesCGBPal0c0 0
#define intro_cat_tilesCGBPal0c1 32767
#define intro_cat_tilesCGBPal0c2 4096
#define intro_cat_tilesCGBPal0c3 4100

/* Gameboy Color palette 1 */
#define intro_cat_tilesCGBPal1c0 0
#define intro_cat_tilesCGBPal1c1 0
#define intro_cat_tilesCGBPal1c2 31744
#define intro_cat_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define intro_cat_tilesCGBPal2c0 32767
#define intro_cat_tilesCGBPal2c1 21887
#define intro_cat_tilesCGBPal2c2 18273
#define intro_cat_tilesCGBPal2c3 8000

/* Gameboy Color palette 3 */
#define intro_cat_tilesCGBPal3c0 0
#define intro_cat_tilesCGBPal3c1 0
#define intro_cat_tilesCGBPal3c2 0
#define intro_cat_tilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define intro_cat_tilesCGBPal4c0 0
#define intro_cat_tilesCGBPal4c1 0
#define intro_cat_tilesCGBPal4c2 0
#define intro_cat_tilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define intro_cat_tilesCGBPal5c0 0
#define intro_cat_tilesCGBPal5c1 0
#define intro_cat_tilesCGBPal5c2 0
#define intro_cat_tilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define intro_cat_tilesCGBPal6c0 0
#define intro_cat_tilesCGBPal6c1 0
#define intro_cat_tilesCGBPal6c2 0
#define intro_cat_tilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define intro_cat_tilesCGBPal7c0 0
#define intro_cat_tilesCGBPal7c1 0
#define intro_cat_tilesCGBPal7c2 2048
#define intro_cat_tilesCGBPal7c3 635
/* Start of tile array. */
extern unsigned char intro_cat_tiles[];

/* End of INTRO_CAT_TILES.H */
