/*

 INTRO_SCREEN_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 74

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define intro_screen_tilesBank 0

/* Super Gameboy palette 0 */
#define intro_screen_tilesSGBPal0c0 511
#define intro_screen_tilesSGBPal0c1 20704
#define intro_screen_tilesSGBPal0c2 12392
#define intro_screen_tilesSGBPal0c3 15

/* Super Gameboy palette 1 */
#define intro_screen_tilesSGBPal1c0 6076
#define intro_screen_tilesSGBPal1c1 8935
#define intro_screen_tilesSGBPal1c2 6596
#define intro_screen_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define intro_screen_tilesSGBPal2c0 6076
#define intro_screen_tilesSGBPal2c1 8935
#define intro_screen_tilesSGBPal2c2 6596
#define intro_screen_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define intro_screen_tilesSGBPal3c0 6076
#define intro_screen_tilesSGBPal3c1 8935
#define intro_screen_tilesSGBPal3c2 6596
#define intro_screen_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define intro_screen_tilesCGBPal0c0 29520
#define intro_screen_tilesCGBPal0c1 32285
#define intro_screen_tilesCGBPal0c2 25849
#define intro_screen_tilesCGBPal0c3 21513

/* Gameboy Color palette 1 */
#define intro_screen_tilesCGBPal1c0 29520
#define intro_screen_tilesCGBPal1c1 32285
#define intro_screen_tilesCGBPal1c2 31132
#define intro_screen_tilesCGBPal1c3 21513

/* Gameboy Color palette 2 */
#define intro_screen_tilesCGBPal2c0 29520
#define intro_screen_tilesCGBPal2c1 15112
#define intro_screen_tilesCGBPal2c2 12935
#define intro_screen_tilesCGBPal2c3 550

/* Gameboy Color palette 3 */
#define intro_screen_tilesCGBPal3c0 29520
#define intro_screen_tilesCGBPal3c1 2051
#define intro_screen_tilesCGBPal3c2 8227
#define intro_screen_tilesCGBPal3c3 3171

/* Gameboy Color palette 4 */
#define intro_screen_tilesCGBPal4c0 32728
#define intro_screen_tilesCGBPal4c1 31636
#define intro_screen_tilesCGBPal4c2 29520
#define intro_screen_tilesCGBPal4c3 17792

/* Gameboy Color palette 5 */
#define intro_screen_tilesCGBPal5c0 16233
#define intro_screen_tilesCGBPal5c1 15112
#define intro_screen_tilesCGBPal5c2 12935
#define intro_screen_tilesCGBPal5c3 11814

/* Gameboy Color palette 6 */
#define intro_screen_tilesCGBPal6c0 11892
#define intro_screen_tilesCGBPal6c1 10769
#define intro_screen_tilesCGBPal6c2 11814
#define intro_screen_tilesCGBPal6c3 8622

/* Gameboy Color palette 7 */
#define intro_screen_tilesCGBPal7c0 29520
#define intro_screen_tilesCGBPal7c1 32728
#define intro_screen_tilesCGBPal7c2 30611
#define intro_screen_tilesCGBPal7c3 3171
/* Start of tile array. */
extern unsigned char intro_screen_tiles[];

/* End of INTRO_SCREEN_TILES.H */
