//AUTOGENERATED FILE FROM png2asset
// Conversion args: /intro_cat_mono.png -o /intro_cat_mono_out.c -use_metafile -map -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 4 -pack_mode casioloopy

#ifndef METASPRITE_intro_cat_mono_out_H
#define METASPRITE_intro_cat_mono_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define intro_cat_mono_out_TILE_ORIGIN 0
#define intro_cat_mono_out_TILE_W 8
#define intro_cat_mono_out_TILE_H 8
#define intro_cat_mono_out_WIDTH 256
#define intro_cat_mono_out_HEIGHT 224
#define intro_cat_mono_out_TILES_WIDTH 32
#define intro_cat_mono_out_TILES_HEIGHT 28
#define intro_cat_mono_out_TILE_COUNT 47
#define intro_cat_mono_out_PALETTE_COUNT 1
#define intro_cat_mono_out_COLORS_PER_PALETTE 16
#define intro_cat_mono_out_TOTAL_COLORS 16
#define intro_cat_mono_out_MAP_ATTRIBUTES 0
#define intro_cat_mono_out_MAP_ATTRIBUTES_WIDTH 32
#define intro_cat_mono_out_MAP_ATTRIBUTES_HEIGHT 28
#define intro_cat_mono_out_MAP_ATTRIBUTES_PACKED_WIDTH 32
#define intro_cat_mono_out_MAP_ATTRIBUTES_PACKED_HEIGHT 28
extern const uint16_t intro_cat_mono_out_map[896];
#define intro_cat_mono_out_map_attributes intro_cat_mono_out_map

BANKREF_EXTERN(intro_cat_mono_out)

extern const palette_color_t intro_cat_mono_out_palettes[16];
extern const uint16_t intro_cat_mono_out_tiles[752];

#endif
