/*

 INTRO_SCREEN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : petris_intro_screen.gbm.tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define intro_screen_mapWidth 20
#define intro_screen_mapHeight 18
#define intro_screen_mapBank 0

#define intro_screen_map intro_screen_mapPLN0
extern unsigned char intro_screen_mapPLN0[];
extern unsigned char intro_screen_mapPLN1[];

/* End of INTRO_SCREEN_MAP.H */
