/*

 INTRO_SCREEN_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : intro_screen_gg_remap.gbm.tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __intro_screen_map_h_INCLUDE
#define __intro_screen_map_h_INCLUDE

#define intro_screen_mapWidth 20
#define intro_screen_mapHeight 18
#define intro_screen_mapBank 0

#define intro_screen_map intro_screen_mapPLN0
extern const unsigned char intro_screen_mapPLN0[];
extern const unsigned char intro_screen_mapPLN1[];

#endif

/* End of INTRO_SCREEN_MAP.H */
