/*

 INTRO_CAT_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 5
   Tile set      : intro_cat.gbm.tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define intro_cat_mapWidth 8
#define intro_cat_mapHeight 5
#define intro_cat_mapBank 0

#define intro_cat_map intro_cat_mapPLN0
extern unsigned char intro_cat_mapPLN0[];
extern unsigned char intro_cat_mapPLN1[];

/* End of INTRO_CAT_MAP.H */
