//AUTOGENERATED FILE FROM png2asset
// Conversion args: /intro_logo_out.png -o /intro_logo_out.c -use_metafile -map -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 1 -pack_mode casioloopy

#ifndef METASPRITE_intro_logo_out_H
#define METASPRITE_intro_logo_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define intro_logo_out_TILE_ORIGIN 0
#define intro_logo_out_TILE_W 8
#define intro_logo_out_TILE_H 8
#define intro_logo_out_WIDTH 224
#define intro_logo_out_HEIGHT 64
#define intro_logo_out_TILES_WIDTH 28
#define intro_logo_out_TILES_HEIGHT 8
#define intro_logo_out_TILE_COUNT 115
#define intro_logo_out_PALETTE_COUNT 1
#define intro_logo_out_COLORS_PER_PALETTE 16
#define intro_logo_out_TOTAL_COLORS 16
#define intro_logo_out_MAP_ATTRIBUTES 0
#define intro_logo_out_MAP_ATTRIBUTES_WIDTH 28
#define intro_logo_out_MAP_ATTRIBUTES_HEIGHT 8
#define intro_logo_out_MAP_ATTRIBUTES_PACKED_WIDTH 28
#define intro_logo_out_MAP_ATTRIBUTES_PACKED_HEIGHT 8
extern const uint16_t intro_logo_out_map[224];
#define intro_logo_out_map_attributes intro_logo_out_map

BANKREF_EXTERN(intro_logo_out)

extern const palette_color_t intro_logo_out_palettes[16];
extern const uint8_t intro_logo_out_tiles[3680];

#endif
