/*

 PET_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 40

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pet_tilesBank 0

/* Super Gameboy palette 0 */
#define pet_tilesSGBPal0c0 0
#define pet_tilesSGBPal0c1 0
#define pet_tilesSGBPal0c2 0
#define pet_tilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define pet_tilesSGBPal1c0 6076
#define pet_tilesSGBPal1c1 8935
#define pet_tilesSGBPal1c2 6596
#define pet_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pet_tilesSGBPal2c0 6076
#define pet_tilesSGBPal2c1 8935
#define pet_tilesSGBPal2c2 6596
#define pet_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pet_tilesSGBPal3c0 6076
#define pet_tilesSGBPal3c1 8935
#define pet_tilesSGBPal3c2 6596
#define pet_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pet_tilesCGBPal0c0 32765
#define pet_tilesCGBPal0c1 15230
#define pet_tilesCGBPal0c2 7964
#define pet_tilesCGBPal0c3 368

/* Gameboy Color palette 1 */
#define pet_tilesCGBPal1c0 32765
#define pet_tilesCGBPal1c1 30378
#define pet_tilesCGBPal1c2 32527
#define pet_tilesCGBPal1c3 20961

/* Gameboy Color palette 2 */
#define pet_tilesCGBPal2c0 32765
#define pet_tilesCGBPal2c1 3939
#define pet_tilesCGBPal2c2 12203
#define pet_tilesCGBPal2c3 11814

/* Gameboy Color palette 3 */
#define pet_tilesCGBPal3c0 32765
#define pet_tilesCGBPal3c1 29949
#define pet_tilesCGBPal3c2 31198
#define pet_tilesCGBPal3c3 17585

/* Gameboy Color palette 4 */
#define pet_tilesCGBPal4c0 32765
#define pet_tilesCGBPal4c1 32696
#define pet_tilesCGBPal4c2 20083
#define pet_tilesCGBPal4c3 7399

/* Gameboy Color palette 5 */
#define pet_tilesCGBPal5c0 16233
#define pet_tilesCGBPal5c1 15112
#define pet_tilesCGBPal5c2 12935
#define pet_tilesCGBPal5c3 11814

/* Gameboy Color palette 6 */
#define pet_tilesCGBPal6c0 11892
#define pet_tilesCGBPal6c1 10769
#define pet_tilesCGBPal6c2 11814
#define pet_tilesCGBPal6c3 8622

/* Gameboy Color palette 7 */
#define pet_tilesCGBPal7c0 32765
#define pet_tilesCGBPal7c1 25368
#define pet_tilesCGBPal7c2 20083
#define pet_tilesCGBPal7c3 0
/* Start of tile array. */
extern unsigned char pet_tiles[];

/* End of PET_TILES.H */
