//AUTOGENERATED FILE FROM png2asset
// Conversion args: /pet_and_special_tiles.png -o /pet_and_special_tiles_out.c -use_metafile -keep_duplicate_tiles -use_map_attributes -keep_palette_order -bpp 4 -max_palettes 1 -pack_mode casioloopy -tiles_only

#ifndef METASPRITE_pet_and_special_tiles_out_H
#define METASPRITE_pet_and_special_tiles_out_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define pet_and_special_tiles_out_TILE_ORIGIN 0
#define pet_and_special_tiles_out_TILE_W 8
#define pet_and_special_tiles_out_TILE_H 16
#define pet_and_special_tiles_out_WIDTH 8
#define pet_and_special_tiles_out_HEIGHT 400
#define pet_and_special_tiles_out_TILES_WIDTH 1
#define pet_and_special_tiles_out_TILES_HEIGHT 25
#define pet_and_special_tiles_out_TILE_COUNT 50
#define pet_and_special_tiles_out_PALETTE_COUNT 1
#define pet_and_special_tiles_out_COLORS_PER_PALETTE 16
#define pet_and_special_tiles_out_TOTAL_COLORS 16

BANKREF_EXTERN(pet_and_special_tiles_out)

extern const palette_color_t pet_and_special_tiles_out_palettes[16];
extern const uint16_t pet_and_special_tiles_out_tiles[800];

#endif
