/*

 PET_TILES_HICONTRAST2.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pet_tiles_hicontras2Bank 0

/* Super Gameboy palette 0 */
#define pet_tiles_hicontras2SGBPal0c0 0
#define pet_tiles_hicontras2SGBPal0c1 0
#define pet_tiles_hicontras2SGBPal0c2 0
#define pet_tiles_hicontras2SGBPal0c3 0

/* Super Gameboy palette 1 */
#define pet_tiles_hicontras2SGBPal1c0 6076
#define pet_tiles_hicontras2SGBPal1c1 8935
#define pet_tiles_hicontras2SGBPal1c2 6596
#define pet_tiles_hicontras2SGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pet_tiles_hicontras2SGBPal2c0 6076
#define pet_tiles_hicontras2SGBPal2c1 8935
#define pet_tiles_hicontras2SGBPal2c2 6596
#define pet_tiles_hicontras2SGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pet_tiles_hicontras2SGBPal3c0 6076
#define pet_tiles_hicontras2SGBPal3c1 8935
#define pet_tiles_hicontras2SGBPal3c2 6596
#define pet_tiles_hicontras2SGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pet_tiles_hicontras2CGBPal0c0 0
#define pet_tiles_hicontras2CGBPal0c1 32767
#define pet_tiles_hicontras2CGBPal0c2 32767
#define pet_tiles_hicontras2CGBPal0c3 0

/* Gameboy Color palette 1 */
#define pet_tiles_hicontras2CGBPal1c0 0
#define pet_tiles_hicontras2CGBPal1c1 31744
#define pet_tiles_hicontras2CGBPal1c2 31744
#define pet_tiles_hicontras2CGBPal1c3 0

/* Gameboy Color palette 2 */
#define pet_tiles_hicontras2CGBPal2c0 0
#define pet_tiles_hicontras2CGBPal2c1 15391
#define pet_tiles_hicontras2CGBPal2c2 15391
#define pet_tiles_hicontras2CGBPal2c3 0

/* Gameboy Color palette 3 */
#define pet_tiles_hicontras2CGBPal3c0 0
#define pet_tiles_hicontras2CGBPal3c1 992
#define pet_tiles_hicontras2CGBPal3c2 2016
#define pet_tiles_hicontras2CGBPal3c3 0

/* Gameboy Color palette 4 */
#define pet_tiles_hicontras2CGBPal4c0 0
#define pet_tiles_hicontras2CGBPal4c1 10570
#define pet_tiles_hicontras2CGBPal4c2 21140
#define pet_tiles_hicontras2CGBPal4c3 32767

/* Gameboy Color palette 5 */
#define pet_tiles_hicontras2CGBPal5c0 16233
#define pet_tiles_hicontras2CGBPal5c1 15112
#define pet_tiles_hicontras2CGBPal5c2 12935
#define pet_tiles_hicontras2CGBPal5c3 11814

/* Gameboy Color palette 6 */
#define pet_tiles_hicontras2CGBPal6c0 11892
#define pet_tiles_hicontras2CGBPal6c1 10769
#define pet_tiles_hicontras2CGBPal6c2 11814
#define pet_tiles_hicontras2CGBPal6c3 8622

/* Gameboy Color palette 7 */
#define pet_tiles_hicontras2CGBPal7c0 32765
#define pet_tiles_hicontras2CGBPal7c1 25368
#define pet_tiles_hicontras2CGBPal7c2 20083
#define pet_tiles_hicontras2CGBPal7c3 0
/* Start of tile array. */
extern unsigned char pet_tiles_hicontras2[];

/* End of PET_TILES_HICONTRAST2.H */
