/*

 PET_TILES_BW.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 55

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pet_tiles_bwBank 0

/* Super Gameboy palette 0 */
#define pet_tiles_bwSGBPal0c0 0
#define pet_tiles_bwSGBPal0c1 0
#define pet_tiles_bwSGBPal0c2 0
#define pet_tiles_bwSGBPal0c3 0

/* Super Gameboy palette 1 */
#define pet_tiles_bwSGBPal1c0 6076
#define pet_tiles_bwSGBPal1c1 8935
#define pet_tiles_bwSGBPal1c2 6596
#define pet_tiles_bwSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pet_tiles_bwSGBPal2c0 6076
#define pet_tiles_bwSGBPal2c1 8935
#define pet_tiles_bwSGBPal2c2 6596
#define pet_tiles_bwSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pet_tiles_bwSGBPal3c0 6076
#define pet_tiles_bwSGBPal3c1 8935
#define pet_tiles_bwSGBPal3c2 6596
#define pet_tiles_bwSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pet_tiles_bwCGBPal0c0 15230
#define pet_tiles_bwCGBPal0c1 32765
#define pet_tiles_bwCGBPal0c2 7964
#define pet_tiles_bwCGBPal0c3 368

/* Gameboy Color palette 1 */
#define pet_tiles_bwCGBPal1c0 6076
#define pet_tiles_bwCGBPal1c1 8935
#define pet_tiles_bwCGBPal1c2 6596
#define pet_tiles_bwCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define pet_tiles_bwCGBPal2c0 6076
#define pet_tiles_bwCGBPal2c1 8935
#define pet_tiles_bwCGBPal2c2 6596
#define pet_tiles_bwCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define pet_tiles_bwCGBPal3c0 6076
#define pet_tiles_bwCGBPal3c1 8935
#define pet_tiles_bwCGBPal3c2 6596
#define pet_tiles_bwCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define pet_tiles_bwCGBPal4c0 6076
#define pet_tiles_bwCGBPal4c1 8935
#define pet_tiles_bwCGBPal4c2 6596
#define pet_tiles_bwCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define pet_tiles_bwCGBPal5c0 6076
#define pet_tiles_bwCGBPal5c1 8935
#define pet_tiles_bwCGBPal5c2 6596
#define pet_tiles_bwCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define pet_tiles_bwCGBPal6c0 6076
#define pet_tiles_bwCGBPal6c1 8935
#define pet_tiles_bwCGBPal6c2 6596
#define pet_tiles_bwCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define pet_tiles_bwCGBPal7c0 6076
#define pet_tiles_bwCGBPal7c1 8935
#define pet_tiles_bwCGBPal7c2 6596
#define pet_tiles_bwCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char pet_tiles_bw[];

/* End of PET_TILES_BW.H */
