/*

 PET_TILES_HC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 55

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pet_tiles_hcBank 0

/* Super Gameboy palette 0 */
#define pet_tiles_hcSGBPal0c0 0
#define pet_tiles_hcSGBPal0c1 0
#define pet_tiles_hcSGBPal0c2 0
#define pet_tiles_hcSGBPal0c3 0

/* Super Gameboy palette 1 */
#define pet_tiles_hcSGBPal1c0 6076
#define pet_tiles_hcSGBPal1c1 8935
#define pet_tiles_hcSGBPal1c2 6596
#define pet_tiles_hcSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pet_tiles_hcSGBPal2c0 6076
#define pet_tiles_hcSGBPal2c1 8935
#define pet_tiles_hcSGBPal2c2 6596
#define pet_tiles_hcSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pet_tiles_hcSGBPal3c0 6076
#define pet_tiles_hcSGBPal3c1 8935
#define pet_tiles_hcSGBPal3c2 6596
#define pet_tiles_hcSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pet_tiles_hcCGBPal0c0 32765
#define pet_tiles_hcCGBPal0c1 863
#define pet_tiles_hcCGBPal0c2 863
#define pet_tiles_hcCGBPal0c3 235

/* Gameboy Color palette 1 */
#define pet_tiles_hcCGBPal1c0 32765
#define pet_tiles_hcCGBPal1c1 32512
#define pet_tiles_hcCGBPal1c2 32512
#define pet_tiles_hcCGBPal1c3 11488

/* Gameboy Color palette 2 */
#define pet_tiles_hcCGBPal2c0 32765
#define pet_tiles_hcCGBPal2c1 16361
#define pet_tiles_hcCGBPal2c2 16233
#define pet_tiles_hcCGBPal2c3 5472

/* Gameboy Color palette 3 */
#define pet_tiles_hcCGBPal3c0 32765
#define pet_tiles_hcCGBPal3c1 31775
#define pet_tiles_hcCGBPal3c2 31775
#define pet_tiles_hcCGBPal3c3 11275

/* Gameboy Color palette 4 */
#define pet_tiles_hcCGBPal4c0 32765
#define pet_tiles_hcCGBPal4c1 32696
#define pet_tiles_hcCGBPal4c2 20083
#define pet_tiles_hcCGBPal4c3 7399

/* Gameboy Color palette 5 */
#define pet_tiles_hcCGBPal5c0 16233
#define pet_tiles_hcCGBPal5c1 15112
#define pet_tiles_hcCGBPal5c2 12935
#define pet_tiles_hcCGBPal5c3 11814

/* Gameboy Color palette 6 */
#define pet_tiles_hcCGBPal6c0 11892
#define pet_tiles_hcCGBPal6c1 10769
#define pet_tiles_hcCGBPal6c2 11814
#define pet_tiles_hcCGBPal6c3 8622

/* Gameboy Color palette 7 */
#define pet_tiles_hcCGBPal7c0 32765
#define pet_tiles_hcCGBPal7c1 25368
#define pet_tiles_hcCGBPal7c2 20083
#define pet_tiles_hcCGBPal7c3 0
/* Start of tile array. */
extern unsigned char pet_tiles_hc[];

/* End of PET_TILES_HC.H */
