/*

 PET_TILES_HICONTRAST.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pet_tiles_hicontrastBank 0

/* Super Gameboy palette 0 */
#define pet_tiles_hicontrastSGBPal0c0 0
#define pet_tiles_hicontrastSGBPal0c1 0
#define pet_tiles_hicontrastSGBPal0c2 0
#define pet_tiles_hicontrastSGBPal0c3 0

/* Super Gameboy palette 1 */
#define pet_tiles_hicontrastSGBPal1c0 6076
#define pet_tiles_hicontrastSGBPal1c1 8935
#define pet_tiles_hicontrastSGBPal1c2 6596
#define pet_tiles_hicontrastSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pet_tiles_hicontrastSGBPal2c0 6076
#define pet_tiles_hicontrastSGBPal2c1 8935
#define pet_tiles_hicontrastSGBPal2c2 6596
#define pet_tiles_hicontrastSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pet_tiles_hicontrastSGBPal3c0 6076
#define pet_tiles_hicontrastSGBPal3c1 8935
#define pet_tiles_hicontrastSGBPal3c2 6596
#define pet_tiles_hicontrastSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pet_tiles_hicontrastCGBPal0c0 0
#define pet_tiles_hicontrastCGBPal0c1 32767
#define pet_tiles_hicontrastCGBPal0c2 32767
#define pet_tiles_hicontrastCGBPal0c3 0

/* Gameboy Color palette 1 */
#define pet_tiles_hicontrastCGBPal1c0 0
#define pet_tiles_hicontrastCGBPal1c1 32224
#define pet_tiles_hicontrastCGBPal1c2 32224
#define pet_tiles_hicontrastCGBPal1c3 0

/* Gameboy Color palette 2 */
#define pet_tiles_hicontrastCGBPal2c0 0
#define pet_tiles_hicontrastCGBPal2c1 15391
#define pet_tiles_hicontrastCGBPal2c2 15391
#define pet_tiles_hicontrastCGBPal2c3 0

/* Gameboy Color palette 3 */
#define pet_tiles_hicontrastCGBPal3c0 0
#define pet_tiles_hicontrastCGBPal3c1 928
#define pet_tiles_hicontrastCGBPal3c2 992
#define pet_tiles_hicontrastCGBPal3c3 0

/* Gameboy Color palette 4 */
#define pet_tiles_hicontrastCGBPal4c0 0
#define pet_tiles_hicontrastCGBPal4c1 10570
#define pet_tiles_hicontrastCGBPal4c2 21140
#define pet_tiles_hicontrastCGBPal4c3 32767

/* Gameboy Color palette 5 */
#define pet_tiles_hicontrastCGBPal5c0 16233
#define pet_tiles_hicontrastCGBPal5c1 15112
#define pet_tiles_hicontrastCGBPal5c2 12935
#define pet_tiles_hicontrastCGBPal5c3 11814

/* Gameboy Color palette 6 */
#define pet_tiles_hicontrastCGBPal6c0 11892
#define pet_tiles_hicontrastCGBPal6c1 10769
#define pet_tiles_hicontrastCGBPal6c2 11814
#define pet_tiles_hicontrastCGBPal6c3 8622

/* Gameboy Color palette 7 */
#define pet_tiles_hicontrastCGBPal7c0 32765
#define pet_tiles_hicontrastCGBPal7c1 25368
#define pet_tiles_hicontrastCGBPal7c2 20083
#define pet_tiles_hicontrastCGBPal7c3 0
/* Start of tile array. */
extern unsigned char pet_tiles_hicontrast[];

/* End of PET_TILES_HICONTRAST.H */
