/*

 .H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : bg_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bg_mapWidth 20
#define bg_mapHeight 18
#define bg_mapBank 0

#define bg_map bg_mapPLN0
extern unsigned char bg_mapPLN0[];
extern unsigned char bg_mapPLN1[];

/* End of .H */
